spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
        '[format_sql]': true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

jwt:
  iss: erichgamma.co.kr
  exp: 24 * 60 * 60 * 1000
  secret: erichgammaerichgammaerichgammaerichgammaerichgamma
