insert into boards (id, board_type) values(1, "review");
insert into boards (id, board_type) values(2, "qna");

insert into users (id, username, password, name, phone, job) values (1, 'Clarinda', 'Boilermaker', 'Chrissie', '230-644-4753', 'Professor');
insert into users (id, username, password, name, phone, job) values (2, 'Culion Island', 'Ironworker', 'Fannie', '372-654-5644', 'Analog Circuit Design manager');
insert into users (id, username, password, name, phone, job) values (3, 'Houma', 'Ironworker', 'Zaria', '921-901-6334', 'Media Manager II');
insert into users (id, username, password, name, phone, job) values (4, 'Recife', 'Tile Setter', 'Alisun', '868-948-4104', 'Budget/Accounting Analyst I');
insert into users (id, username, password, name, phone, job) values (5, 'Sege', 'Plasterers', 'Pennie', '940-551-8764', 'Financial Analyst');
insert into users (id, username, password, name, phone, job) values (6, 'Nacala', 'Millwright', 'Gertruda', '517-268-7651', 'VP Marketing');
insert into users (id, username, password, name, phone, job) values (7, 'Tobermorey', 'Safety Officer', 'Harli', '136-238-7702', 'VP Sales');
insert into users (id, username, password, name, phone, job) values (8, 'Mende/Brénoux', 'HVAC', 'Rosalia', '524-152-5660', 'Help Desk Technician');
insert into users (id, username, password, name, phone, job) values (9, 'Bouarfa', 'Refridgeration', 'Eugenie', '913-369-7000', 'Executive Secretary');
insert into users (id, username, password, name, phone, job) values (10, 'Bucharest', 'Sheet Metal Worker', 'Nina', '688-278-3563', 'Payment Adjustment Coordinator');
insert into users (id, username, password, name, phone, job) values (11, 'Kepi-Papua Island', 'Tile Setter', 'Ashley', '595-588-1044', 'Geologist III');
insert into users (id, username, password, name, phone, job) values (12, 'Cairo', 'Waterproofer', 'Antonia', '202-338-4567', 'Tax Accountant');
insert into users (id, username, password, name, phone, job) values (13, 'Butare', 'Plasterers', 'Martita', '978-322-8638', 'Engineer I');
insert into users (id, username, password, name, phone, job) values (14, 'Buenaventura', 'Welder', 'Min', '472-388-3046', 'Human Resources Assistant II');
insert into users (id, username, password, name, phone, job) values (15, 'opera', 'Equipment Operator', 'Antonie', '658-863-0908', 'Physical Therapy Assistant');

insert into articles (id, writer_id, board_id, title, content ) values (1, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), , 'Halloween II', 'Fire Protection');
insert into articles (id, writer_id, board_id, title, content ) values (2, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Stationmaster Is on Fire - The Movie, That Is!, The (Stinsen brinner... filmen alltså)', 'Framing (Steel)');
insert into articles (id, writer_id, board_id, title, content ) values (3, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Crows Zero II (Kurôzu Zero II)', 'Epoxy Flooring');
insert into articles (id, writer_id, board_id, title, content ) values (4, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Die Weihnachtsklempner', 'Temp Fencing, Decorative Fencing and Gates');
insert into articles (id, writer_id, board_id, title, content ) values (5, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Lucky Night', 'Roofing (Asphalt)');
insert into articles (id, writer_id, board_id, title, content ) values (6, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Maidens'' Conspiracy, The (Tirante el Blanco)', 'Fire Sprinkler System');
insert into articles (id, writer_id, board_id, title, content ) values (7, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Ballast', 'Sitework & Site Utilities');
insert into articles (id, writer_id, board_id, title, content ) values (8, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Maid, The (Nana, La)', 'Fire Sprinkler System');
insert into articles (id, writer_id, board_id, title, content ) values (9, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Forever Young', 'Structural & Misc Steel Erection');
insert into articles (id, writer_id, board_id, title, content ) values (10, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Bad Blood: A Cautionary Tale ', 'Drywall & Acoustical (MOB)');
insert into articles (id, writer_id, board_id, title, content ) values (11, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Blackbeard''s Ghost', 'Doors, Frames & Hardware');
insert into articles (id, writer_id, board_id, title, content ) values (12, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Beautiful Boy', 'Asphalt Paving');
insert into articles (id, writer_id, board_id, title, content ) values (13, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Safe House', 'Site Furnishings');
insert into articles (id, writer_id, board_id, title, content ) values (14, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Fled', 'Masonry & Precast');
insert into articles (id, writer_id, board_id, title, content ) values (15, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Sense of History, A', 'Drilled Shafts');
insert into articles (id, writer_id, board_id, title, content ) values (16, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Vacation from Marriage', 'Construction Clean and Final Clean');
insert into articles (id, writer_id, board_id, title, content ) values (17, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), '1969', 'Electrical');
insert into articles (id, writer_id, board_id, title, content ) values (18, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Spartacus', 'Termite Control');
insert into articles (id, writer_id, board_id, title, content ) values (19, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Beauty of the Day (Belle de jour)', 'Ornamental Railings');
insert into articles (id, writer_id, board_id, title, content ) values (20, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Rape of Europa, The', 'Elevator');
insert into articles (id, writer_id, board_id, title, content ) values (21, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Sorcerer and the White Snake, The (Bai she chuan shuo)', 'Electrical and Fire Alarm');
insert into articles (id, writer_id, board_id, title, content ) values (22, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'From the Clouds to the Resistance (Dalla nube alla resistenza)', 'Granite Surfaces');
insert into articles (id, writer_id, board_id, title, content ) values (23, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Garçu, Le', 'Asphalt Paving');
insert into articles (id, writer_id, board_id, title, content ) values (24, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Money Money Money (L''aventure, c''est l''aventure)', 'Termite Control');
insert into articles (id, writer_id, board_id, title, content ) values (25, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'My Friend Ivan Lapshin (Moy drug Ivan Lapshin)', 'Framing (Wood)');
insert into articles (id, writer_id, board_id, title, content ) values (26, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'What Price Hollywood?', 'Masonry');
insert into articles (id, writer_id, board_id, title, content ) values (27, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Hearts of Darkness: A Filmmakers Apocalypse', 'EIFS');
insert into articles (id, writer_id, board_id, title, content ) values (28, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Kronos (a.k.a. Captain Kronos: Vampire Hunter)', 'Structural and Misc Steel (Fabrication)');
insert into articles (id, writer_id, board_id, title, content ) values (29, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Birdman', 'Exterior Signage');
insert into articles (id, writer_id, board_id, title, content ) values (30, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Little Girl Who Lives Down the Lane, The', 'Fire Sprinkler System');
insert into articles (id, writer_id, board_id, title, content ) values (31, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Sudden Wealth of the Poor People of Kombach, The (Der plötzliche Reichtum der armen Leute von Kombach)', 'Framing (Steel)');
insert into articles (id, writer_id, board_id, title, content ) values (32, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Cry, The (Grido, Il)', 'Prefabricated Aluminum Metal Canopies');
insert into articles (id, writer_id, board_id, title, content ) values (33, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Bungee Jumping of Their Own (Beonjijeompeureul hada)', 'Wall Protection');
insert into articles (id, writer_id, board_id, title, content ) values (34, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Bill Hicks: Revelations', 'HVAC');
insert into articles (id, writer_id, board_id, title, content ) values (35, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Quatsch und die Nasenbärbande', 'Drywall & Acoustical (FED)');
insert into articles (id, writer_id, board_id, title, content ) values (36, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'In Passing', 'Glass & Glazing');
insert into articles (id, writer_id, board_id, title, content ) values (37, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Roaring Twenties, The', 'RF Shielding');
insert into articles (id, writer_id, board_id, title, content ) values (38, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Midnight (Primeiro Dia, O)', 'Granite Surfaces');
insert into articles (id, writer_id, board_id, title, content ) values (39, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Sansho the Bailiff (Sanshô dayû)', 'Termite Control');
insert into articles (id, writer_id, board_id, title, content ) values (40, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Cinderella', 'Elevator');
insert into articles (id, writer_id, board_id, title, content ) values (41, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'American Idiots', 'Masonry & Precast');
insert into articles (id, writer_id, board_id, title, content ) values (42, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Last Hurrah for Chivalry (Hao xia)', 'Overhead Doors');
insert into articles (id, writer_id, board_id, title, content ) values (43, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Take the High Ground!', 'Drywall & Acoustical (FED)');
insert into articles (id, writer_id, board_id, title, content ) values (44, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Tales of Terror (Kaidan Shin Mimibukuro)', 'Masonry');
insert into articles (id, writer_id, board_id, title, content ) values (45, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Kevin Smith: Too Fat For 40', 'Retaining Wall and Brick Pavers');
insert into articles (id, writer_id, board_id, title, content ) values (46, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Ghost and Mr. Chicken, The', 'Painting & Vinyl Wall Covering');
insert into articles (id, writer_id, board_id, title, content ) values (47, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Last Song, The', 'Casework');
insert into articles (id, writer_id, board_id, title, content ) values (48, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'In Harm''s Way', 'Wall Protection');
insert into articles (id, writer_id, board_id, title, content ) values (49, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Club Fed', 'Masonry');
insert into articles (id, writer_id, board_id, title, content ) values (50, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Dirty Dozen, The', 'Doors, Frames & Hardware');
insert into articles (id, writer_id, board_id, title, content ) values (51, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Twice Upon a Time', 'Glass & Glazing');
insert into articles (id, writer_id, board_id, title, content ) values (52, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Nobody Else But You (Poupoupidou)', 'Framing (Steel)');
insert into articles (id, writer_id, board_id, title, content ) values (53, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Triplets of Belleville, The (Les triplettes de Belleville)', 'Electrical and Fire Alarm');
insert into articles (id, writer_id, board_id, title, content ) values (54, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Sunset Park', 'Overhead Doors');
insert into articles (id, writer_id, board_id, title, content ) values (55, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Trapped in Paradise', 'Waterproofing & Caulking');
insert into articles (id, writer_id, board_id, title, content ) values (56, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Lemming', 'Temp Fencing, Decorative Fencing and Gates');
insert into articles (id, writer_id, board_id, title, content ) values (57, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Love Is a Woman (Death Is a Woman)', 'Construction Clean and Final Clean');
insert into articles (id, writer_id, board_id, title, content ) values (58, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Frankie Starlight', 'Drywall & Acoustical (MOB)');
insert into articles (id, writer_id, board_id, title, content ) values (59, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Fantasticks, The', 'Structural & Misc Steel Erection');
insert into articles (id, writer_id, board_id, title, content ) values (60, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Sebastian Maniscalco: What''s Wrong with People?', 'Roofing (Asphalt)');
insert into articles (id, writer_id, board_id, title, content ) values (61, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Tenure', 'Retaining Wall and Brick Pavers');
insert into articles (id, writer_id, board_id, title, content ) values (62, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Sun Kissed', 'Temp Fencing, Decorative Fencing and Gates');
insert into articles (id, writer_id, board_id, title, content ) values (63, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Assassination Tango', 'Epoxy Flooring');
insert into articles (id, writer_id, board_id, title, content ) values (64, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Pink Panther, The', 'Fire Protection');
insert into articles (id, writer_id, board_id, title, content ) values (65, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Never Back Down', 'Drywall & Acoustical (MOB)');
insert into articles (id, writer_id, board_id, title, content ) values (66, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Hunting of the President, The', 'Hard Tile & Stone');
insert into articles (id, writer_id, board_id, title, content ) values (67, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Tabu: A Story of the South Seas', 'Wall Protection');
insert into articles (id, writer_id, board_id, title, content ) values (68, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Norte, the End of History', 'Ornamental Railings');
insert into articles (id, writer_id, board_id, title, content ) values (69, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Nothing Left to Fear', 'Prefabricated Aluminum Metal Canopies');
insert into articles (id, writer_id, board_id, title, content ) values (70, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Shanghai', 'Temp Fencing, Decorative Fencing and Gates');
insert into articles (id, writer_id, board_id, title, content ) values (71, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Magnificent Seven Ride!, The', 'Rebar & Wire Mesh Install');
insert into articles (id, writer_id, board_id, title, content ) values (72, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Zombie Honeymoon', 'Landscaping & Irrigation');
insert into articles (id, writer_id, board_id, title, content ) values (73, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'West (Occident)', 'Epoxy Flooring');
insert into articles (id, writer_id, board_id, title, content ) values (74, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Miracle on 34th Street', 'Site Furnishings');
insert into articles (id, writer_id, board_id, title, content ) values (75, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Man of the Year', 'Glass & Glazing');
insert into articles (id, writer_id, board_id, title, content ) values (76, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Cat Returns, The (Neko no ongaeshi)', 'Site Furnishings');
insert into articles (id, writer_id, board_id, title, content ) values (77, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Blackbeard''s Ghost', 'Ornamental Railings');
insert into articles (id, writer_id, board_id, title, content ) values (78, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Love Forbidden (Défense d''aimer)', 'Overhead Doors');
insert into articles (id, writer_id, board_id, title, content ) values (79, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Son of the Sheik, The', 'Drywall & Acoustical (MOB)');
insert into articles (id, writer_id, board_id, title, content ) values (80, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Buster Keaton: A Hard Act to Follow', 'Structural and Misc Steel (Fabrication)');
insert into articles (id, writer_id, board_id, title, content ) values (81, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Woman''s Secret, A', 'HVAC');
insert into articles (id, writer_id, board_id, title, content ) values (82, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Reckoning, The', 'EIFS');
insert into articles (id, writer_id, board_id, title, content ) values (83, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Short Circuit 2', 'Ornamental Railings');
insert into articles (id, writer_id, board_id, title, content ) values (84, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Barry Lyndon', 'Fire Sprinkler System');
insert into articles (id, writer_id, board_id, title, content ) values (85, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'People on Sunday (Menschen am Sonntag)', 'Structural & Misc Steel Erection');
insert into articles (id, writer_id, board_id, title, content ) values (86, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Robin Hood', 'Drilled Shafts');
insert into articles (id, writer_id, board_id, title, content ) values (87, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'The Strength of Water', 'Framing (Steel)');
insert into articles (id, writer_id, board_id, title, content ) values (88, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Ogre, The (Unhold, Der)', 'Fire Sprinkler System');
insert into articles (id, writer_id, board_id, title, content ) values (89, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Idiocracy', 'Drywall & Acoustical (FED)');
insert into articles (id, writer_id, board_id, title, content ) values (90, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'My Night At Maud''s (Ma Nuit Chez Maud)', 'Elevator');
insert into articles (id, writer_id, board_id, title, content ) values (91, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Roommates', 'Exterior Signage');
insert into articles (id, writer_id, board_id, title, content ) values (92, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Decoder', 'Fire Protection');
insert into articles (id, writer_id, board_id, title, content ) values (93, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Tenacious D in The Pick of Destiny', 'Construction Clean and Final Clean');
insert into articles (id, writer_id, board_id, title, content ) values (94, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Punch-Drunk Love', 'Fire Protection');
insert into articles (id, writer_id, board_id, title, content ) values (95, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Decision at Sundown', 'Temp Fencing, Decorative Fencing and Gates');
insert into articles (id, writer_id, board_id, title, content ) values (96, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Amador', 'Fire Protection');
insert into articles (id, writer_id, board_id, title, content ) values (97, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Fame', 'Plumbing & Medical Gas');
insert into articles (id, writer_id, board_id, title, content ) values (98, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Revengers Tragedy', 'Structural & Misc Steel Erection');
insert into articles (id, writer_id, board_id, title, content ) values (99, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Arnold', 'Masonry');
insert into articles (id, writer_id, board_id, title, content ) values (100, 1 + FLOOR(RAND() % 15), 1 + FLOOR(RAND() % 2), 'Return to the 36th Chamber (Shao Lin da peng da shi) ', 'Wall Protection');